### PR TITLE
Include margin-top to the navbar, review README.

### PR DESCRIPTION
**Pull request by billodiallo**
the requirements of this project consists of making a clone of a New York Times article page.
It has different sections :
- navbar
- main
- footer
- iframe

### CODE REVIEW

**Review by mahmoud717 — CHANGES_REQUESTED** [review]
### Changes required ♻️ 

**Hello @billodiallo  & @ashraffares**

Great job with the project so far it looks amazing, but there are still some changes to be made:
 
---
### Requested 🔴 

- [ ] Please make sure to fix all of your linters errors.
- [ ] your Pull request must have a descriptive name and description.
- [ ] The project must have a professional readme file.


---

please make these changes and request another code review.

if you have any questions don't hesitate to contact me on slack **MahmoudMohammad**

**Review by SpaYco — CHANGES_REQUESTED** [review]
# Changes Requested 

Hello Team! 👋 
Awesome job so far!! 👍 you still need to make some changes though! 

## Required Changes ♻️ 

- [ ] you haven't done of what the previous TSE asked, please make sure you do those changes before you ask for another code review 

### please make the appropriate changes and ask for another code review ✔️ 

Happy Coding!

Best, 
Aziz Mejri 
_contact me on [twitter](https://twitter.com/iSpaYco) or slack (@SpaYco) if you need any help_

**Review by Georjane — CHANGES_REQUESTED** [review]
## Status: Changes Required 🛑 🔧
### Hi there✋🏽
Nicely done. You have done a great job on the New York Times project. 
However, you still have a couple of changes to make.

- [ ] Please add a description to this pull request. Your description can talk about what your project is all about and some methods and techniques you used to work on the project.  Pull Request has a meaningful title and a brief description 


Optional
- [ ] The project should have a descriptive README.md with the help of Markdown language. See this template example recommended by Microverse that you can copy and edit to suit you.  [(screenshot from Pathwright)](https://github.com/microverseinc/readme-template)

Feel free to reach out to me on slack if you have any questions, Witah Georjane 🤝
Good luck and Happy Coding 💻

**Review by Georjane — CHANGES_REQUESTED** [review]
## Status: Changes Required 🔧
### Hi There ✋🏽

- [ ] Nice work, your ReadMe file looks good but it can look better. Using the previous link of the proposed standard by Microverse for the Readme in the last review, you can improve your readme file and make it professional by simply forking [this Readme Template](https://github.com/microverseinc/readme-template):

that way, your author's section for example will look like this:
author1
which looks more presentable than this:
author2

- [ ] This pull request description just says **_'project 1'_**! Please add more description to it. Pull Request should have a meaningful title and a brief description ([Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/49736080/)) before a project can be approved.

Feel free to reach out to me on slack if you have any questions, Witah Georjane 🤝

Good luck on your project and Happy Coding 💻

**Comment by billodiallo** [comment]
Hello Witah Georjane,
I Submitted my work for the last rewiew but you did not approved online , Kindly approve I am still waiting for you to fill the form .

**Review by kobiyoyo — CHANGES_REQUESTED** [review]
## Hi Team    
#### Great Job so far, everything works fine, but there are a few more things required. 
### General 
- [ ] Lets include a readme.MD file (Very important)
- [ ] Your pull request should be descriptive
- [ ] Let's add margin-top to the nav bar


### Make changes and submit another code review request.
*Happy coding* 
(Any questions Feel free to contact me on slack @kobiyoyo)

**Comment by billodiallo** [comment]
@kobiyoyo 
changes done.

**Review by umairarshadbutt — CHANGES_REQUESTED** [review]
# Status: REQUIRED CHANGES :warning: :construction: 

Hi @billodiallo 
Good job with the changes! :tada: We are almost there.
We, however, do have a few changes to carry out before we proceed (see review comment).

##

Kindly work on the suggested changes 👇.
- [ ] Please add a descriptive README.md and PR description([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/general/descriptive_readme.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/66243643/))
**Hints:**
1. Read and understand about PR. Please Visit for [PR](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/66243642/)
2. Please visit for the README [template](https://github.com/microverseinc/readme-template)


##
- **When you have made the specified changes, please submit another code review. Thank you!**
##
**If you are stuck at any point or have any questions, let me know by leaving a comment here and mentioning me. I will be happy to help**
HAPPY CODING :computer:
**[Umair Arshad](https://umairarshad.me/)**
[Twitter](https://twitter.com/its_UmairArshad) | [LinkedIn](https://www.linkedin.com/in/umair-arshad-butt/) | [GitHub](https://github.com/umairarshadbutt)

**Review by ElijahTobs — CHANGES_REQUESTED** [review]
# Status: Changes Required :recycle: 

## Hi @billodiallo :wave: 

You've done well so far :+1:  and I commend you for that :clap: 
However, there are still some changes to be made before this project can be approved.

## REQUIRED

* [ ] Please, make all the changes as requested by the previous TSE.
* [ ] The items at the top left corner of your navbar should be properly aligned and should be towards the extreme left of the navbar just like it is on the original page.
* [ ] You should have the NY Times image logo embedded in the center of your navbar ([link to page](https://www.nytimes.com/2014/03/18/science/space/detection-of-waves-in-space-buttresses-landmark-theory-of-big-bang.html?_r=0)) ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/html_css/positioning_and_floating_elements/positioning_and_floating_requirements.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/59538403/))
* [ ] The NY Times logo should be a link ([link to page](https://www.nytimes.com/2014/03/18/science/space/detection-of-waves-in-space-buttresses-landmark-theory-of-big-bang.html?_r=0)) ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/html_css/positioning_and_floating_elements/positioning_and_floating_requirements.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/59538403/))
* [ ] The `SUBSCRIBE` and `LOGIN` buttons should also be towards the extreme right of the navbar
* [ ] The telescope picture should be centred.
* [ ] The **Editor's Pick** section is nowhere to be found. You should use [`<aside>` tag](https://www.w3schools.com/tags/tag_aside.asp) for `Editor's picks` section on the righmost side. ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/html_css/positioning_and_floating_elements/aside_requirement.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/59538403/))
* [ ] Add the following sections:
  * [ ] Suggested newsletters for you
  * [ ] Most Popular
  * [ ] More in Space and Astronomy
  * [ ] Editor's Picks


image

### Make the requested changes and submit for another review.
## Happy Coding :computer: 

_Feel free to reach out to me on slack_ **`@Elijah Ayandokun`**
  **Elijah O. Ayandokun**
[Github](https://github.com/ElijahTobs) | [LinkedIn](https://www.linkedin.com/in/ayandokunelijah/) | [Twitter](https://twitter.com/ElijahTobs)

**Comment by billodiallo** [comment]
all changes requested done

**Review by Srjnnnn — CHANGES_REQUESTED** [review]
## Status: Changes Required :recycle: 
Hello team. Thanks for making the requested changes from previous TSEs. Your page looks good and you are nearly there. However, before this, I'd like to suggest some more optional things that can be done to improve this page. Also some mandatory things. :smile: 

### Mandatory

- [ ]  I think you've given a Readme template. You can improve your readme using this template and please remove the live link from your readme. It doesn't work.
- [ ]  Again on your readme put your license as a link. Add the necessary headings to every section and make it look very professional. As an example, I am giving one of my [repos](https://github.com/eypsrcnuygr/book-an-appointmen-frontend).
- [ ]  There is no editor's pick section as an aside tag. Kindly add this.

### Optional (However, highly recommended)
From my understanding, you've managed to do most of the mandatory requirements. Even so, to grasp to idea positioning better and make your page look like more to the original page, please consider working on them. Also, I can't guarantee that the next TSE, who will review this PR, will take them as optional. :smile: 

- [ ] Place ' Space Ripples Reveal Big Bang’s Smoking Gun' section properly to the image and the social icons behind it as well.
- [ ]  Decrease the width of the theory of inflation and make it like the original.
- [ ]  Place the video in the center.
- [ ] Decrease the width of the suggested newsletter part and the footer and make it look like as in the original page.

Once you've done those changes, please submit for a re-review.
If you've any questions, feel free to reach me via Slack. :100: 
_Eyüp Sercan UYGUR_

**Comment by billodiallo** [comment]
Mandatory and optional changes done.
please check

**Comment by billodiallo** [comment]
@eypsrcnuygr
Mandatory and optional changes done

**Review by Srjnnnn — CHANGES_REQUESTED** [review]
## Status: Changes Required :recycle: 
Hello team! Thanks for making some of the changes. Again I have to tell you that it is my perspective and if anyone else would do this review, they might expect those optional changes as mandatory. Keep in mind that. There is one thing. I have to expect and am giving an image as well.
footer

- [ ]  This one is not placed correctly. It has a blank space on the right. Please center it and decrease the width of it.
- [ ] some of the optional changes are still waiting to be done. I highly recommend decreasing the width of the necessary components to make it like the original page.

Please address those issues, and when you'll be done, submit for a re-review.
If you have any questions about the review, feel free to reach me via Slack. :100: 
_Eyüp Sercan UYGUR_

**Comment by billodiallo** [comment]
@eypsrcnuygr 
changes done.
thank you for your reviews, it makes my project  better.

**Comment by Srjnnnn** [comment]
There is one more small issue and misunderstanding. I am reviewing it not now will tell you the small problem. And then I believe you're ready to go. @billodiallo

**Review by Srjnnnn — CHANGES_REQUESTED** [review]
## Status: CHanges Required :recycle: 
Hello. Thanks for your hard work and for making the requested changes. :smile: 

There is a misunderstanding when I told you that there needs to be an aside tag as editor's picks section, I've talked about this part. :arrow_double_down: 
aside

I don't want to make you spend your time with small details but since it's one of the hard requirements, kindly add this to your page.
aside2

After making the requested changes, please submit for a re-review.
_Eyüp Sercan UYGUR_

**Comment by billodiallo** [comment]
@eypsrcnuygr added last feedback.
thanks for review I learned a lot and you make me more comfortable writing code .

**Comment by billodiallo** [comment]
@eypsrcnuygr  DONE

**Review by Srjnnnn — APPROVED** [review]
## Status: Approved :tada: :partying_face: 
Hello again. Thanks for making the requested changes. 

You can merge and continue to the next project. :+1: 
_Eyüp Sercan UYGUR_

**Comment by billodiallo** [comment]
@eypsrcnuygr  thank you for the review and all the team.

**Pull request merged**
